version: 0.2

phases:
  install:
    commands:
      # Install dependencies for the test phase
      - apt-get update && apt-get install -y openjdk-11-jre-headless
      - pip install -r requirements.txt
      # Setup for Docker commands in the build phase
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  build:
    commands:
      # Test phase
      - echo Running tests...
      - python -m pytest tests/

  post_build:
    commands:
      # Deploy phase or any cleanup tasks
      - echo Build and push completed on `date`

cache:
  paths:
    - '.cache/pip'
    - 'venv/'

artifacts:
  files:
    # Specify any files or artifacts that you want to output from your build process, if any.

    
